apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: nginx
  type: {{ .Values.service.type }}