name: Helm Chart Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.0.0'
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: kondensmelkcr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Package Helm Chart
      run: |
        helm package ./test1
        helm repo index ./ --url https://kondensmelkcr.azurecr.io/helm/v1
    
    - name: Push Helm Chart to Azure Container Registry
      run: |
        az acr helm push ./test1.tar.gz --force -n kondensmelkcr
    
    - name: Update Helm Chart Repository
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update Helm Chart Repository"
        git push
